export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const NEW_POST_FAIL = "NEW_POST_FAIL";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_LOADING = "NEW_POST_LOADING";

export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";
export const NEW_COMMENT_LOADING = "NEW_COMMENT_LOADING";

export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";

export const ADD_DISLIKE = "ADD_DISLIKE";
export const REMOVE_DISLIKE = "REMOVE_DISLIKE";
